services:
  - type: web
    name: apiscout
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: GEMINI_API_KEY_1
        sync: false
      - key: GEMINI_API_KEY_2
        sync: false
      - key: GEMINI_API_KEY_3
        sync: false
      - key: GEMINI_API_KEY_4
        sync: false
      - key: GEMINI_API_KEY_5
        sync: false
      - key: GEMINI_API_KEY_6
        sync: false
      - key: GEMINI_API_KEY_7
        sync: false
      - key: GEMINI_API_KEY_8
        sync: false